name: Install fagram-bin with yay

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Update system and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed base-devel git --noconfirm

      - name: Install yay (AUR helper)
        run: |
          git clone https://aur.archlinux.org/yay.git
          cd yay
          makepkg -si --noconfirm

      - name: Install fagram-bin package
        run: |
          yay -S fagram-bin --noconfirm

      - name: Echo job result
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "Installation succeeded"
          else
            echo "Installation failed"
          fi
