name: Install fagram-bin with yay

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Update system and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed base-devel git --noconfirm

      - name: Create non-root user for building
        run: |
          useradd -m builder

      - name: Install yay (AUR helper)
        run: |
          # Clone yay into builder's home directory and adjust permissions
          git clone https://aur.archlinux.org/yay.git /home/builder/yay
          chown -R builder:builder /home/builder/yay
          cd /home/builder/yay
          # Run makepkg as the non-root user
          su builder -c 'makepkg -si --noconfirm'

      - name: Install fagram-bin package
        run: |
          su builder -c 'yay -S fagram-bin --noconfirm'

      - name: Echo job result
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "Installation succeeded"
          else
            echo "Installation failed"
          fi
