name: Install fagram-bin

on: [push]

jobs:
  manual-install:
    runs-on: ubuntu-latest
    container: archlinux/archlinux
    steps:
      - name: Update package database
        run: pacman -Syu --noconfirm
      - name: Install base-devel, git, and sudo
        run: pacman -S --noconfirm base-devel git sudo
      - name: Create builder user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: /usr/bin/pacman" >> /etc/sudoers
      - name: Clone AUR repository as builder
        run: su builder -c "git clone https://aur.archlinux.org/fagram-bin.git ~/fagram-bin"
      - name: Build and install fagram-bin as builder
        run: su builder -c "cd ~/fagram-bin && makepkg -si --noconfirm"

  yay-install:
    runs-on: ubuntu-latest
    container: archlinux/archlinux
    steps:
      - name: Update package database
        run: pacman -Syu --noconfirm
      - name: Install base-devel, git, and sudo
        run: pacman -S --noconfirm base-devel git sudo
      - name: Create builder user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: /usr/bin/pacman" >> /etc/sudoers
      - name: Clone yay AUR repository as builder
        run: su builder -c "git clone https://aur.archlinux.org/yay.git ~/yay"
      - name: Build and install yay as builder
        run: su builder -c "cd ~/yay && makepkg -si --noconfirm"
      - name: Install fagram-bin using yay as builder
        run: su builder -c "yay -S fagram-bin --noconfirm"
