name: Run Python Script

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RPM repository dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.bvPAT }}
          repository: burhancodes/fagram-rpm
          event-type: new-release
